### ISSUE TITLE
charset panics 

### ISSUE THREAD

**Issue by Akibalogh** [advancedlogic/GoOse#21]
I'm seeing panics in certain situations at line 66 on crawler.go.
I made a fork, will see if I can fix or workaround. But any thoughts appreciated

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x444624]

goroutine 198 [running]:
io/ioutil.func·002()
        /root/.gvm/gos/go1.4rc2/src/io/ioutil/ioutil.go:30 +0x103
bytes.(*Buffer).ReadFrom(0xc20c2b1340, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4rc2/src/bytes/buffer.go:169 +0x254
io/ioutil.readAll(0x0, 0x0, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4rc2/src/io/ioutil/ioutil.go:33 +0x1b0
io/ioutil.ReadAll(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/.gvm/gos/go1.4rc2/src/io/ioutil/ioutil.go:42 +0x68
github.com/marketmuse/GoOse.Crawler.Crawl(0x7dd470, 0x0, 0x1194, 0x101, 0x7ec390, 0x2, 0x825570, 0x10, 0x8255b0, 0x11, ...)
        /root/.gvm/pkgsets/go1.4rc2/global/src/github.com/marketmuse/GoOse/crawler.go:66 +0xf53
github.com/marketmuse/GoOse.Goose.ExtractFromRawHtml(0x7dd470, 0x0, 0x1194, 0x101, 0x7ec390, 0x2, 0x825570, 0x10, 0x8255b0, 0x11, ...)
        /root/.gvm/pkgsets/go1.4rc2/global/src/github.com/marketmuse/GoOse/goose.go:21 +0x12b
```

**Comment by Akibalogh** [comment]
fix proposed in https://github.com/advancedlogic/GoOse/pull/23
